### ISSUE TITLE
Game time not working

### ISSUE THREAD

**Issue by ghost** [fatalis/LiveSplit.Amnesia#1]
Hey,

I tried your script and game few problems. First of all when using Compare again game time, splits just show -, not the actually time. Second issue is when close the game while this asl script is still active and try re-open it, then game will crash.

Event Viewer doesn't show anything helpful, just that this amnesia crashed.

Any way to fix this?

**Comment by fatalis** [comment]
the game was probably updated and I don't maintain this project anymore, sorry

**Comment by ghost** [comment]
Found solution, need unpatch amnesia ---> https://www.speedrun.com/tdd/resources
